### ISSUE TITLE
Project Task List

### ISSUE THREAD

**Issue by izaiasmachado** [izaiasmachado/simple-auth#1]
- [ ] **Backend**
   - [ ] Initial Setup
      - [ ] Express and Cors
      - [ ] MongoDB and Mongoose
      - [ ] JsonWebToken authorization

   - [ ] User Model
      - [ ] Name
      - [ ] Email
      - [ ] Password - Will be hashed with Bcrypt

   - [ ] User Controller
      - [ ] Index - Signin
      - [ ] Store - Signup
