### ISSUE TITLE
Project Task List

### ISSUE THREAD

**Issue by izaiasmachado** [izaiasmachado/simple-auth#1]
- [ ] **Setup Development Environment**
   - [ ] [Express](https://expressjs.com), [Cors](https://www.npmjs.com/package/cors) and [Mongoose](https://mongoosejs.com/)
   - [ ] [Docker](https://docker.com/)
   - [ ] [MongoDB](https://www.mongodb.com/)

---

- [ ] **Components**
   - [ ] User
   - [ ] Auth
